version: '3.8'

services:
  lumira-web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lumira-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/lumira
    networks:
      - lumira-network
    environment:
      - DB_HOST=mcp-postgres
      - DB_PORT=5432
      - DB_NAME=lumira
      - DB_USER=postgres
      - DB_PASS=10_Jime_10

  lumira-nginx:
    image: nginx:alpine
    container_name: lumira-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/lumira
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lumira-network
    depends_on:
      - lumira-web

networks:
  lumira-network:
    external: true
    name: homelab-backup_mcp-network
